{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "nextjs-app.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "nextjs-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "nextjs-app.selectorLabels" . | nindent 4 }}
{{- end }}
