# Development environment values
replicaCount: 1

image:
  repository: nextjs-frontend-template
  pullPolicy: IfNotPresent
  tag: "dev"

serviceAccount:
  create: true
  annotations:
    # Required for Vault integration
  name: "nextjs-frontend-template"

# Vault Agent Injector annotations
podAnnotations:
  vault.hashicorp.io/agent-inject: "true"
  vault.hashicorp.io/role: "nextjs-frontend-template"
  vault.hashicorp.io/agent-inject-secret-env: "secret/data/nextjs-frontend-template/development"
  vault.hashicorp.io/agent-inject-template-env: |
    {{- with secret "secret/data/nextjs-frontend-template/development" -}}
    export NEXTAUTH_URL="{{ .Data.data.NEXTAUTH_URL }}"
    export NEXTAUTH_SECRET="{{ .Data.data.NEXTAUTH_SECRET }}"
    export DATABASE_URL="{{ .Data.data.DATABASE_URL }}"
    export API_URL="{{ .Data.data.API_URL }}"
    {{- end -}}

env:
  - name: NODE_ENV
    value: "development"
  - name: NEXT_PUBLIC_ENV
    value: "development"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: dev.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nextjs-app-dev-tls
      hosts:
        - dev.example.com

autoscaling:
  enabled: false
